### ISSUE TITLE
yew 0.22 Support

### ISSUE THREAD

**Issue by Coruu** [ctron/yew-oauth2#50]
It looks like yew-oauth2 v0.12.1 dosn't work with yew 0.22 .  
Using the example code I get a lot of errors like:
```
error[E0277]: the trait bound `impl Hook<Output = Option<Agent<...>>>: Hook` is not satisfied
  --> src/app.rs:18:17
   |
18 |     let agent = use_auth_agent().expect("Requires OAuth2Context component in parent h...
   |                 --------------^^
   |                 |
   |                 the trait `Hook` is not implemented for `impl Hook<Output = Option<Agent
   |                 required by a bound introduced by this call
   |
note: there are multiple different versions of crate `yew` in the dependency graph
  --> /home/benjamin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yew-0.22.0/src/functio
   |
31 | pub trait Hook {
   | ^^^^^^^^^^^^^^ this is the required trait
   |
  ::: src/app.rs:1:5
   |
 1 | use yew::prelude::*;
   |     --- one version of crate `yew` used here, as a direct dependency of the current crat
 2 | use yew_nested_router::{components::*, prelude::*};
   |     ----------------- one version of crate `yew` used here, as a dependency of crate `ye
   |
  ::: /home/benjamin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yew-0.21.0/src/functio
   |
 6 | pub trait TearDown: Sized + 'static {
   | ----------------------------------- this is the found trait
   = help: you can use `cargo tree` to explore your dependency tree
   = note: the full name for the type has been written to '/home/benjamin/work/peer-retro/web/ta
   = note: consider using `--verbose` to print the full type name to the console

error[E0277]: the trait bound `yew_nested_router::Router<AppRoute>: yew::Component` is not sa
   --> src/app.rs:36:14
    |
 36 |             <Router<AppRoute>>
    |              ^^^^^^ the trait `yew::Component` is not implemented for `yew_nested_route
    |
note: there are multiple different versions of crate `yew` in the dependency graph
   --> /home/benjamin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yew-0.22.0/src/html/c
    |
123 | pub trait Component: Sized + 'static {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this is the required trait
    |
   ::: src/app.rs:1:5
    |
  1 | use yew::prelude::*;
    |     --- one version of crate `yew` used here, as a direct dependency of the current cra
  2 | use yew_nested_router::{components::*, prelude::*};
    |     ----------------- one version of crate `yew` used here, as a dependency of crate `y
    |
   ::: /home/benjamin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yew-nested-router-0.7
    |
175 | pub struct Router<T: Target> {
    | ---------------------------- this type doesn't implement the required trait
    |
   ::: /home/benjamin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yew-0.21.0/src/functi
    |
  6 | pub trait TearDown: Sized + 'static {
    | ----------------------------------- this is the found trait
    = help: you can use `cargo tree` to explore your dependency tree
    = note: required for `yew_nested_router::Router<AppRoute>` to implement `yew::BaseCompone
    = note: this error originates in the macro `html` (in Nightly builds, run with -Z macro-b

error[E0277]: the trait bound `yew_oauth2::components::Failure: yew::Component` is not satisf
   --> src/app.rs:37:18
    |
 37 |                 <Failure>
    |                  ^^^^^^^ the trait `yew::Component` is not implemented for `yew_oauth2:
    |
note: there are multiple different versions of crate `yew` in the dependency graph
   --> /home/benjamin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yew-0.22.0/src/html/c
    |
123 | pub trait Component: Sized + 'static {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this is the required trait
    |
   ::: src/app.rs:1:5
    |
  1 | use yew::prelude::*;
    |     --- one version of crate `yew` used here, as a direct dependency of the current cra
  2 | use yew_nested_router::{components::*, prelude::*};
    |     ----------------- one version of crate `yew` used here, as a dependency of crate `y
    |
   ::: /home/benjamin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yew-oauth2-0.12.1/src
    |
 22 | #[function_component(Failure)]
    | ------------------------------ this type doesn't implement the required trait
    |
   ::: /home/benjamin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yew-0.21.0/src/functi
    |
  6 | pub trait TearDown: Sized + 'static {
    | ----------------------------------- this is the found trait
    = help: you can use `cargo tree` to explore your dependency tree
    = note: required for `yew_oauth2::components::Failure` to implement `yew::BaseComponent`
    = note: this error originates in the macro `html` (in Nightly builds, run with -Z macro-b

error[E0277]: the trait bound `yew_oauth2::components::FailureMessage: yew::Component` is not
   --> src/app.rs:40:30
    |
 40 | ...                   <FailureMessage />
    |                        ^^^^^^^^^^^^^^ the trait `yew::Component` is not implemented for
    |
note: there are multiple different versions of crate `yew` in the dependency graph
   --> /home/benjamin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yew-0.22.0/src/html/c
    |
123 | pub trait Component: Sized + 'static {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this is the required trait
    |
   ::: src/app.rs:1:5
    |
  1 | use yew::prelude::*;
    |     --- one version of crate `yew` used here, as a direct dependency of the current cra
  2 | use yew_nested_router::{components::*, prelude::*};
    |     ----------------- one version of crate `yew` used here, as a dependency of crate `y
    |
   ::: /home/benjamin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yew-oauth2-0.12.1/src
    |
 57 | #[function_component(FailureMessage)]
    | ------------------------------------- this type doesn't implement the required trait
    |
   ::: /home/benjamin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yew-0.21.0/src/functi
    |
  6 | pub trait TearDown: Sized + 'static {
    | ----------------------------------- this is the found trait
    = help: you can use `cargo tree` to explore your dependency tree
    = note: required for `yew_oauth2::components::FailureMessage` to implement `yew::BaseComp
    = note: this error originates in the macro `html` (in Nightly builds, run with -Z macro-b

error[E0599]: the function or associated item `new` exists for struct `VChild<yew_oauth2::com
  --> src/app.rs:40:30
   |
40 | ...                   <FailureMessage />
   |                        ^^^^^^^^^^^^^^ function or associated item cannot be called on `V
   |
  ::: /home/benjamin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yew-oauth2-0.12.1/src/
   |
57 | #[function_component(FailureMessage)]
   | ------------------------------------- doesn't satisfy `_: BaseComponent` or `_: Componen
   |
   = note: the following trait bounds were not satisfied:
           `yew_oauth2::components::FailureMessage: yew::Component`
           which is required by `yew_oauth2::components::FailureMessage: yew::BaseComponent`
   = note: this error originates in the macro `html` (in Nightly builds, run with -Z macro-ba

error[E0599]: the function or associated item `new` exists for struct `VChild<yew_oauth2::com
  --> src/app.rs:37:18
   |
37 |                 <Failure>
   |                  ^^^^^^^ function or associated item cannot be called on `VChild<yew_oau
   |
  ::: /home/benjamin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yew-oauth2-0.12.1/src/
   |
22 | #[function_component(Failure)]
   | ------------------------------ doesn't satisfy `_: BaseComponent` or `yew_oauth2::compon
   |
   = note: the following trait bounds were not satisfied:
           `yew_oauth2::components::Failure: yew::Component`
           which is required by `yew_oauth2::components::Failure: yew::BaseComponent`
   = note: this error originates in the macro `html` (in Nightly builds, run with -Z macro-ba
```

Can we get an update for yew 0.22?

**Comment by ctron** [comment]
I guess it was to be ported over. I won't have much time for that at the moment unfortunately. I'd be happy to assist in any PR though.

**Comment by Coruu** [comment]
@ctron i did the update, but turns out yew-nested-router needs an update first so i can update the examples in yew-oauth2.

I opend an mr over at https://github.com/ctron/yew-nested-router/pull/20 with a update for yew-nested-router to yew 0.22. 
Once that is merged I'll update the examples and open the mr with the update here.
